module.exports = {
    name: 'Vue.js',
    value: 'vue',
    files: [
        'package.json',
        '.editorconfig',
        '.eslintrc.js',
        'babel.config.js',
        'postcss.config.js',
        'webpack.config.js',
        'src/html/index.ejs',
        'src/index.js',
        'src/App.vue',
    ],
    dependencies: [],
    devDependencies: [
        '@babel/core',
        '@babel/plugin-syntax-dynamic-import',
        '@babel/preset-env',
        '@gridonic/webpack',
        'autoprefixer',
        'babel-eslint',
        'core-js',
        'cssnano',
        'eslint',
        'eslint-config-airbnb-base',
        'eslint-import-resolver-webpack',
        'eslint-loader',
        'eslint-plugin-import',
        'eslint-plugin-vue',
        'fast-async',
        'postcss-lh',
        'postcss-replace',
    ]
};
